language: node_js
node_js:
  - "10"
before_install:
  - npm i -g npm
  - npm i -g lerna
  - npm i -g yarn
install:
  - lerna bootstrap
  - yarn build
brefore_deploy:
  - yarn build
  - - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script:
    - yarn publish
  on:
    branch: master
    tags: true
    repo: KoyamaSohei/dzfu
